services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8004:8004"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8004
